### ISSUE TITLE
Environment Overhaul for Monday

### ISSUE THREAD

**Issue by mrod9000** [bi3mer/gmap377_leathGloves_inc#145]
@BernardSheeran @WillReardon @insanity180 @nacciavatti @myself as well.

For Modeling purposes: Triangulated Dodecahedrons first, then manipulate to create rocks of varying sizes. - Small, Medium, Large, Preferable.

When you start creating an asset say what you're making on Slack.

Spend at least 4 hours making as many environment assets as you can. Before SUNDAY NIGHT

https://docs.google.com/document/d/1sb80M331Sj2qKjVuzU6MrgjcyLn6-VAG-_8GtupZBR8/edit

**Comment by rowlandsc** [comment]
@mrod9000 @BernardSheeran @insanity180 @nacciavatti @WillReardon @vdetommaso
