### ISSUE TITLE
Power Ups

### ISSUE THREAD

**Issue by rowlandsc** [bi3mer/gmap377_leathGloves_inc#17]

**Comment by bi3mer** [comment]
Double damage, what other power-ups are there? Shield?

**Comment by bfawber** [comment]
That's what we have written so far from our meetings.

Maybe we could have some sort of power up that would upgrade your current weapon for a brief amount of time, like
Rockets: have more push back/Damage
Mines: bigger range, higher damage
Beam: Further reach, multiple shot at once??
default laser: more damage, shoot multiple, etc.

something along those lines. I'll try to think of different power ups too.

**Comment by bfawber** [comment]
[InfiniteSkies_Perspective_Powerup_List_1.08.16.docx](https://files.zenhub.io/56915ddafe71427b3ca6ab09)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by bfawber** [comment]
All power ups implemented, now I just need the models.
#94 #95 #96 #97 + speed boost and shield power up models
