### ISSUE TITLE
Everyone play the game and LEAVE ONE THING YOU SEE WRONG OR WOULD LIKE TO SEE IMPROVED.

### ISSUE THREAD

**Issue by rowlandsc** [bi3mer/gmap377_leathGloves_inc#175]

**Comment by BernardSheeran** [comment]
I feel like the forces when you are hit by enemies are a bit to strong, if have the misfortune of enemies consistently hitting you you end up with little control of the player model as its pushed around like a hockey puck

**Comment by rawhat** [comment]
Submitted two bugs with AI, one rotation and one movement behavior.

Also, I think we should add strafing?  Shouldn't be too hard.

**Comment by rowlandsc** [comment]
Reticules not a set size

**Comment by paperclip007** [comment]
#221
