### ISSUE TITLE
Kamakazi's Flying Through Mesh

### ISSUE THREAD

**Issue by BernardSheeran** [bi3mer/gmap377_leathGloves_inc#189]
kamakzi enemys are flying through the mesh and constantly hitting the player, who is unable to move due to the pushing forces.

term 2 week 4 build on website. 

played on PC master race

**Comment by rowlandsc** [comment]
Also does it for some tanks as well
But some enemies use pathfinding correctly

**Comment by bi3mer** [comment]
Fixed
