### ISSUE TITLE
Concept Art

### ISSUE THREAD

**Issue by BernardSheeran** [bi3mer/gmap377_leathGloves_inc#21]
Concept Art for Desert Boss (First Planet)- Scorpion like

**Comment by mrod9000** [comment]
![scorpinox_splash](https://cloud.githubusercontent.com/assets/16549938/12226958/447bf3f6-b7f2-11e5-9ce6-2f63aeb08abd.jpg)
![vectorized concept art](https://cloud.githubusercontent.com/assets/16549938/12226961/478437a2-b7f2-11e5-87c7-c99649398b1c.jpg)
