### ISSUE TITLE
3 Rock Obelisks for Desert Planet

### ISSUE THREAD

**Issue by mrod9000** [bi3mer/gmap377_leathGloves_inc#210]
http://imgc.allpostersimages.com/images/P-473-488-90/87/8786/4HPT300Z/posters/obelisk-on-attuf-ridge-petra-jordon-1st-c-b-c-carved-rock-6-metres-high.jpg

https://docs.google.com/document/d/1sb80M331Sj2qKjVuzU6MrgjcyLn6-VAG-_8GtupZBR8/edit

**Comment by bi3mer** [comment]
I'm just not good enough
