### ISSUE TITLE
Two Obelisks

### ISSUE THREAD

**Issue by BernardSheeran** [bi3mer/gmap377_leathGloves_inc#226]
One man-made in ground, Egyptian themed with indents instead of hieroglyphs since we dont have that shit yet lol.

One more smooth/crystally and more floaty based off the 

https://www.google.com/search?q=obelisk&espv=2&biw=1666&bih=911&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiZ8ZTeuNLKAhXMOSYKHfxUDxcQ_AUIBigB#tbm=isch&q=floating+crystal+obelisk&imgdii=pluZsMuHxYIw7M%3A%3BpluZsMuHxYIw7M%3A%3Bu5aIohFyWPF7tM%3A&imgrc=pluZsMuHxYIw7M%3A

**Comment by insanity180** [comment]
Modeled but need colliiders still. Group consesus was the 2nd and 6th one in the pic I sent in the chat.

**Comment by insanity180** [comment]
Now in Unity in the Environment Prefabs folder with colliders
