### ISSUE TITLE
Animation for Tri-Drone

### ISSUE THREAD

**Issue by mrod9000** [bi3mer/gmap377_leathGloves_inc#243]
Rig/Animate walking cycle

**Comment by insanity180** [comment]
Going on the back burner, first water

**Comment by insanity180** [comment]
Pushing off for now, this will take a good bit of time to complete but I can do it next week with what I am assigned or just later on in development. Especially since Cody does not want this to be walking on the surface so it may need a remodel.

**Comment by insanity180** [comment]
In Unity. Colliders and Prefab made with Controller. Controller has two states, Idle or Fly. To my knowledge the purpose of these guys are like the Kamakazi enemies and therefore need no attack animation. Can create if necessary this week.
