### ISSUE TITLE
Animation for Ice Tank Enemy

### ISSUE THREAD

**Issue by mrod9000** [bi3mer/gmap377_leathGloves_inc#245]
Rig/Animate Attack Movement

**Comment by insanity180** [comment]
Animated, gonna get animation review tomorrow (Saturday) from the group and then do a game exporter and set up it's Animator

**Comment by insanity180** [comment]
Thought I animated the right one but supposedly tank enemy in EnemyModels folder is not the right one (according to Colan) so..... waiting to hear for Vince

**Comment by insanity180** [comment]
Reanimated with new model
