### ISSUE TITLE
3 Ice Environment Assets

### ISSUE THREAD

**Issue by mrod9000** [bi3mer/gmap377_leathGloves_inc#246]
Create 3 Assets for the Ice Planet, these images can be used as reference/inspiration. We are aiming for the sharp spiky structures that jolt out of the ground

http://jpgames.de/wp-content/uploads/2012/05/lost-planet-3-konzept-4.jpg

http://66.147.244.133/~natehall/wordpress/wp-content/uploads/2013/06/1370543861MP_BG01.jpg

http://www.iamag.co/features/itsart/wp-content/uploads/2013/09/lost-planet-3-p20.jpg

-All Maya files should be on the Git (.ma) and you aren't done until you checked and put the prefab in Unity successfully.

Once in unity checks how it looks and apply the Ice material to it.

**Comment by BernardSheeran** [comment]
this has been up a while whats the deal, done? not?

**Comment by nacciavatti** [comment]
the unity prefabs have been in their respective folders for small/medium/large ice rock and clusters also the structures for the ice planet have been on github. All of these were uploaded on 02/21/2016
