### ISSUE TITLE
Alien Mushroom Models for Swamp Planet

### ISSUE THREAD

**Issue by mrod9000** [bi3mer/gmap377_leathGloves_inc#250]
So I remembered before how you made mushroom characters for your old game, and was wondering if you could create some fungi/mushroom like assets for the Swamp Planet.

I couldn't really find much concept art, but i'm sure you get the idea. Two mushrooms like these, and we can make small, medium and large versions

![mushrom_concept_art](https://cloud.githubusercontent.com/assets/16549938/12806737/a57834d4-cad6-11e5-8bc3-19b638c74c02.jpg)

http://www.blogcdn.com/blog.moviefone.com/media/2009/06/alice0302-(2).jpg

**Comment by BernardSheeran** [comment]
you thinking concept art or models?

**Comment by mrod9000** [comment]
Models

**Comment by mrod9000** [comment]
Models
