### ISSUE TITLE
Crystal objects need to be re prefabed with correct centers

### ISSUE THREAD

**Issue by rowlandsc** [bi3mer/gmap377_leathGloves_inc#303]
Colliders do not apply properly to them. To be able to be dropped to planet and procedurally placed it needs to have a collider centered

**Comment by rowlandsc** [comment]
I believe you made this @BernardSheeran  can you just fix them real quick

**Comment by rowlandsc** [comment]
The bunch crystals in particular I am referring to.

**Comment by BernardSheeran** [comment]
crystals have been re exported
