### ISSUE TITLE
This rock jawn is not centered so we cant currently use it

### ISSUE THREAD

**Issue by rowlandsc** [bi3mer/gmap377_leathGloves_inc#304]
![screen shot 2016-02-06 at 2 06 46 pm](https://cloud.githubusercontent.com/assets/9440888/12868855/1a2cdca4-ccde-11e5-8847-6ad3b39a1d1f.png)

**Comment by rowlandsc** [comment]
I believe you made this @BernardSheeran can you just fix them real quick

**Comment by BernardSheeran** [comment]
model has been re exported
