### ISSUE TITLE
Enemy rocket explosion radiuses way bigger than the radius of the explosion effect

### ISSUE THREAD

**Issue by paperclip007** [bi3mer/gmap377_leathGloves_inc#306]
When an enemy rocket explodes near you, you can still be damaged by it even if you're way outside the apparent radius of the explosion (where the particle effect is). Either the radius needs to be decreased or we need a bigger particle effect.

**Comment by rowlandsc** [comment]
@bi3mer change blast radius to better represent particle effect aka lower the damage radius of the rockets/artill
