### ISSUE TITLE
Motion Base, Disconnect

### ISSUE THREAD

**Issue by bi3mer** [bi3mer/gmap377_leathGloves_inc#355]
Error occurs between menu and game during loading. 

"Basically there are times when it's loading when whatever thread in Unity that runs the motion base code is't running and communicating with the motion base, and I think that's the problem" Alex

**Comment by paperclip007** [comment]
I think the problem is that the procedural generation is all done in a single frame. If it were spread out over several frames, I think that would solve the disconnect issues. #400

**Comment by paperclip007** [comment]
I don't know if Laura ever did this, but whatever
