### ISSUE TITLE
Planet Orientation Bug Thing

### ISSUE THREAD

**Issue by mrod9000** [bi3mer/gmap377_leathGloves_inc#356]
![screen_shot_2016-02-13_at_9 00 30_pm_480](https://cloud.githubusercontent.com/assets/16549938/13185501/78d7d764-d70f-11e5-80f0-071967f426fa.png)

**Comment by mrod9000** [comment]
I will look into this again and get specifics on what happend/what objects

**Comment by paperclip007** [comment]
I think this is fixed
