### ISSUE TITLE
Saving and loading the game does not work. I click continue and it breaksssssssss

### ISSUE THREAD

**Issue by rowlandsc** [bi3mer/gmap377_leathGloves_inc#380]
@microlm tagging since you were looking into this too

**Comment by rowlandsc** [comment]
@paperclip007 actually after 2 min load it started me on the second planet where I left off

**Comment by rowlandsc** [comment]
but all of the objects are screwed up with the procedural gen see issue #376

**Comment by paperclip007** [comment]
This isn't an issue with continuing, it's an issue with playing a game a second time without restarting. The infinite loading thing happens whether you pick new game or continue, it doesn't matter which.  This leads me to think it has nothing to do with loading/saving.

**Comment by rowlandsc** [comment]
Is it tied to Proc gen?

**Comment by paperclip007** [comment]
#399
