### ISSUE TITLE
Hover Tank

### ISSUE THREAD

**Issue by rowlandsc** [bi3mer/gmap377_leathGloves_inc#6]

**Comment by bi3mer** [comment]
Tentative for now, still have to look into physics materials for ice and that kindof stuff

**Comment by rawhat** [comment]
Pushed basic functionality for hovering
Doesn't play nicely with the other movement scripts, but we can look into that or changing mine

**Comment by rowlandsc** [comment]
Maybe look into this @rawhat https://www.assetstore.unity3d.com/en/#!/content/18490

**Comment by bi3mer** [comment]
Decided it wasn't worth the effort
