### ISSUE TITLE
Skybox/ Atmosphere of Planet Alpha

### ISSUE THREAD

**Issue by BernardSheeran** [bi3mer/gmap377_leathGloves_inc#77]
Currently there is no atmosphere on Planet Alpha, we just see deep space. I suggest altering the skybox to resemble a blue sky and we can see the other planets  in the distance.
![planet-site-in-the-sky-23295-1920x1080 1](https://cloud.githubusercontent.com/assets/15163066/12218176/ab02865c-b6e5-11e5-9d78-e625dba1a460.jpg)

**Comment by rowlandsc** [comment]
Skybox not changing.

**Comment by rowlandsc** [comment]
Already assigned to me
