### ISSUE TITLE
Environment Assets for Planet Beta

### ISSUE THREAD

**Issue by BernardSheeran** [bi3mer/gmap377_leathGloves_inc#81]
model any environment assets needed to achieve the desired aesthetic of the planet. (would look great if you started modeling in tris from the beginning to get more dynamic lighting effects on the models.

**Comment by mrod9000** [comment]
Model environment assets for the Desert Planet. Rocks, rocky formations, stones the general stuff we described in class.

**Comment by rowlandsc** [comment]
@BernardSheeran 
Help Nick with this

**Comment by rowlandsc** [comment]
@nacciavatti @BernardSheeran Break this down into a pipeline

**Comment by rowlandsc** [comment]
@mrod9000
