### ISSUE TITLE
Go to Sound Presentation

### ISSUE THREAD

**Issue by mrod9000** [bi3mer/gmap377_leathGloves_inc#93]
CopyPasta from the email sent to us, here's just a reminder to go to it if you have time. --
Meet & Greet The Music Industry Audio Post Crew (January 12, 5:00PM): Meet a crew of students who are interested in scoring, sound effects, foley, and audio mixing. These students are willing to help create soundtracks and sound effects for your games.

Location: URBN Center Room 141

**Comment by insanity180** [comment]
I had class during the start of this and missed it, if no one else went I will see if there was a list of attendees to see if we can contact.
