### ISSUE TITLE
Multi Shot Power Up Model

### ISSUE THREAD

**Issue by mrod9000** [bi3mer/gmap377_leathGloves_inc#95]
Multi-Shot
Will upgrade all or the current active weapon to shoot 3 shots instead of just 1 for X (default 30 seconds?) amount of time. 

Need:
-3D pick-up model
-dashboard icon

**Comment by insanity180** [comment]
![Screen Shot 2016-01-22 at 4.04.37 PM.png](https://files.zenhub.io/56a2998399aeaa64327c3c81)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
